version: '3.9'

services:
  # go-app:
  #   container_name: ${APP_CONTAINER_NAME}
  #   build: 
  #     context: .
  #     dockerfile: ./build/app/Dockerfile
  #   tty: true 
  #   depends_on:
  #     - postgres-db
  #   ports:
  #     - ${APP_PORT}:8080

  postgres-db:
    container_name: ${DB_HOST}
    build:
      context: .
      dockerfile: ./build/db/Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432

  postgres-gui:
    image: sosedoff/pgweb
    container_name: "pgweb"
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db

volumes:
  postgres-data: